/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import static Cliente.FrmPrincipal.contenedor;
import javax.swing.ImageIcon;

/**
 *
 * @author GUADALUPE
 */
public class FrmPreguntas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPreguntas
     */
    String rpta; int valorChk;
    
    public FrmPreguntas() {
        initComponents();
    }
    
    public void tipo(int valor){
        ImageIcon url;
        valorChk = valor;
        //VALOR INDICA SI ES DE MATEMÁTICA, VOCACIÓN, ETC
        switch (valor){
            case 1:
                int ejer = (int) (Math.random() * 4) + 1; //INDICA CUÁL DE LAS 4 PREGUNTAS APARECE

                url = new ImageIcon ("src\\imagenes\\Preguntas\\Mate\\"+ejer+".jpg");
                System.out.println(url);
                lblFoto.setIcon(url);
                if (ejer == 1){
                    rpta = "34";   
                }
                if (ejer == 2){
                    rpta = "-3";   
                }
                if (ejer == 3){
                    rpta = "10";   
                }
                if (ejer == 4){
                    rpta = "C";   
                }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        txtRpta = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(txtRpta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRpta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        System.out.println(rpta);
        FrmTest obj = new FrmTest();
        if (!(txtRpta.getText().equalsIgnoreCase(rpta))){
            contenedor.add(obj);
            obj.setVisible(true);
            obj.bloquearChk(valorChk);
            this.dispose();
        }else{
            contenedor.add(obj);
            obj.setVisible(true);
            obj.desbloquearChk(valorChk);
            this.dispose();
        }
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtRpta;
    // End of variables declaration//GEN-END:variables
}
