/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import static Cliente.FrmPrincipal.contenedor;
import Negocio.Registro;
import Negocio.Test;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prolog.Prolog;

/**
 *
 * @author USAT
 */
public class FrmResultados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmResultados
     */
    public FrmResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCivil = new javax.swing.JButton();
        btnAmbiental = new javax.swing.JButton();
        btnIndustrial = new javax.swing.JButton();
        btnMedicina = new javax.swing.JButton();
        btnDerecho = new javax.swing.JButton();
        btnContabilidad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("E-mail");

        tblRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblRes);

        jLabel2.setText("Información sobre las carreras");

        btnCivil.setText("Ing. Civil");
        btnCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCivilActionPerformed(evt);
            }
        });

        btnAmbiental.setText("Ing. Ambiental");
        btnAmbiental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbientalActionPerformed(evt);
            }
        });

        btnIndustrial.setText("Ing. Industrial");
        btnIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndustrialActionPerformed(evt);
            }
        });

        btnMedicina.setText("Medicina");
        btnMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinaActionPerformed(evt);
            }
        });

        btnDerecho.setText("Derecho");
        btnDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechoActionPerformed(evt);
            }
        });

        btnContabilidad.setText("Contabilidad");
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAmbiental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIndustrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedicina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCivil)
                    .addComponent(btnAmbiental)
                    .addComponent(btnIndustrial))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContabilidad)
                    .addComponent(btnDerecho)
                    .addComponent(btnMedicina))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int posAlumno = Registro.validarUser(txtEmail.getText(), txtPass.getText());
        
        if (posAlumno !=-1) {
            resultado();
        }else{
            JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS", "MENSAJE DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCivilActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(1);
    }//GEN-LAST:event_btnCivilActionPerformed

    private void btnAmbientalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbientalActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(2);
    }//GEN-LAST:event_btnAmbientalActionPerformed

    private void btnDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechoActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(5);
    }//GEN-LAST:event_btnDerechoActionPerformed

    private void btnIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndustrialActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(3);
    }//GEN-LAST:event_btnIndustrialActionPerformed

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(4);
    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void btnMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinaActionPerformed
        FrmInfo obj = new FrmInfo();
        FrmPrincipal.contenedor.add(obj);
        obj.toFront();
        obj.setVisible(true);
        obj.carrera(6);
    }//GEN-LAST:event_btnMedicinaActionPerformed

    private void resultado(){
        
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Carrera");
                
        Vector carreras =new Vector();
        carreras = Test.resultadoPersonal(txtEmail.getText());
        
        
        Object datos[][]=new Object[1][2];
        for(int i=0;i<carreras.size();i++){
            Test obj = (Test)carreras.get(i);
            datos[0][0]=obj.getFecha();
            datos[0][1]=obj.getResultado();
            
            modelo.addRow(datos[0]);
        }
        tblRes.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbiental;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCivil;
    private javax.swing.JButton btnContabilidad;
    private javax.swing.JButton btnDerecho;
    private javax.swing.JButton btnIndustrial;
    private javax.swing.JButton btnMedicina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRes;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
