/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import static Cliente.FrmPrincipal.contenedor;
import Negocio.Registro;
import Negocio.Test;
import java.awt.Checkbox;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import org.jpl7.Term;
import prolog.Prolog;

/**
 *
 * @author GUADALUPE
 */
public class FrmTest extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_principal
     */
    
    JDPreguntas obj = new JDPreguntas(null, true);
        
    public FrmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chkAtencion = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        chk7 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        chkHabilidadNum = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        chk1.setText("Matemático");
        chk1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chk1StateChanged(evt);
            }
        });
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.setText("Dominio espacial");

        chk3.setText("Dominio del habla");
        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });

        chkAtencion.setText("Vocación de servicio");
        chkAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtencionActionPerformed(evt);
            }
        });

        chk5.setText("Relaciones interpersonales");

        chk6.setText("Manejo de software");
        chk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk6ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Seleccione todos los adjetivos que \ndescriban su personalidad. Señale \ntantos como desee, trate de definirse \ntal como es, no como le gustaría ser.");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("E-mail:");

        chk7.setText("Buen vocabulario");
        chk7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk7ActionPerformed(evt);
            }
        });

        chk8.setText("Razonamiento Matematico");
        chk8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk8ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        chkHabilidadNum.setText("Habilidad Numérica");
        chkHabilidadNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabilidadNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtemail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(chk8)
                                    .addComponent(chkAtencion)
                                    .addComponent(chk3)
                                    .addComponent(chk2)
                                    .addComponent(chk1)
                                    .addComponent(chk5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(chk7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chk6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(chkHabilidadNum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(chk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAtencion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHabilidadNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
        // TODO add your handling code here:
        
        if(chk1.isSelected()==true){
            llamarForm(1);
        }
       
    }//GEN-LAST:event_chk1ActionPerformed

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        // TODO add your handling code here:
        if(chk3.isSelected()==true){
            llamarForm(3);
        }
    }//GEN-LAST:event_chk3ActionPerformed

    private void chkAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAtencionActionPerformed

    private void chk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int posAlumno = Registro.buscarAlumno(txtemail.getText());
        
        if (posAlumno !=-1) {
            Prolog.limpiezaprolog();
            if(chk1.isSelected()){
                Prolog.insertaopc("matematico", "si");
            }else{
                Prolog.insertaopc("matematico", "no");
            }
            if(chkHabilidadNum.isSelected()){
                Prolog.insertaopc("hab_numerica", "si");
            }else{
                Prolog.insertaopc("hab_numerica", "no");
            }
            if(chkAtencion.isSelected()){
                Prolog.insertaopc("atencion", "si");
            }else{
                Prolog.insertaopc("atencion", "no");
            }
            if(chk2.isSelected()){
                Prolog.insertaopc("domesp", "si");
            }else{
                Prolog.insertaopc("domesp", "no");
            }
            if(chk3.isSelected()){
                Prolog.insertaopc("domhabla", "si");
            }else{
                Prolog.insertaopc("domhabla", "no");
            }
            if(chkAtencion.isSelected()){
                Prolog.insertaopc("vocserv", "si");
            }else{
                Prolog.insertaopc("vocserv", "no");
            }
            if(chk5.isSelected()){
                Prolog.insertaopc("relinter", "si");
            }else{
                Prolog.insertaopc("relinter", "no");
            }
            if(chk6.isSelected()){
                Prolog.insertaopc("mansw", "si");
            }else{
                Prolog.insertaopc("mansw", "no");
            }
            Prolog.reglas(txtemail.getText());
            JOptionPane.showMessageDialog(null, "TEST REGISTRADO", "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
            
            FrmResultados interfaz = new FrmResultados();
            FrmPrincipal.contenedor.add(interfaz);
            this.setVisible(false);
            interfaz.toFront();
            interfaz.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "ALUMNO NO REGISTRADO", "MENSAJE DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        txtemail.setText("");
        chk1.setSelected(false);
        chk2.setSelected(false);
        chk3.setSelected(false);
        chkAtencion.setSelected(false);
        chk5.setSelected(false);
        chk6.setSelected(false);
        chkHabilidadNum.setSelected(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void llamarForm(int valor){
        obj.tipo(valor);
        //contenedor.add(obj);
        obj.setVisible(true);
        this.setVisible(false);
    }
    public static void bloquearChk(int chk){ 
        switch(chk){
            case 1:
                chk1.setSelected(false);
                chk1.setEnabled(false);
                break;
            case 3:
                chk3.setSelected(false);
                chk3.setEnabled(false);
                break;
            case 4:
                chkAtencion.setSelected(false);
                chkAtencion.setEnabled(false);
                break;
            case 7:
                chk7.setSelected(false);
                chk7.setEnabled(false);
                break;
            case 8:
                chk8.setSelected(false);
                chk8.setEnabled(false);
                break;
            case 10:
                chkHabilidadNum.setSelected(false);
                chkHabilidadNum.setEnabled(false);
                break;
        }
       
        /*
        if(chk == 1){
            chk1.setSelected(false);
            chk1.setEnabled(false);
        }
        else{
            if(chk == 3){
                chk3.setSelected(false);
                chk3.setEnabled(false);
            }
            else{
                if(chk == 7){
                    chk7.setSelected(false);
                    chk7.setEnabled(false);
                }
                 else{
                    if(chk == 8){
                        chk8.setSelected(false);
                        chk8.setEnabled(false);
                    }
                }
            }
        }
        */
        
        
    }
    public static void desbloquearChk(int chk){
              
         switch(chk){
            case 1:
                chk1.setSelected(true);
                chk1.setEnabled(false);
                break;
            case 3:
                chk3.setSelected(true);
                chk3.setEnabled(false);
                break;
            case 7:
                chk7.setSelected(true);
                chk7.setEnabled(false);
                break;
            case 8:
                chk8.setSelected(true);
                chk7.setEnabled(false);
                break;          
        }
        
         /*
         if(chk == 1){
            chk1.setSelected(true);
            chk1.setEnabled(false);
        }
        else{
            if(chk == 3){
                chk3.setSelected(true);
                chk3.setEnabled(false);
            }
            else{
                if(chk == 7){
                    chk7.setSelected(true);
                    chk7.setEnabled(false);
                }
                 else{
                    if(chk == 8){
                        chk8.setSelected(true);
                        chk8.setEnabled(false);
                    }
                }
            }
        }
        */

    }
    
    private void chk1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chk1StateChanged
        // TODO add your handling code here:  
    }//GEN-LAST:event_chk1StateChanged

    private void chk7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk7ActionPerformed
        // TODO add your handling code here:
        if(chk7.isSelected()==true){
            llamarForm(7);
        }
    }//GEN-LAST:event_chk7ActionPerformed

    private void chk8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk8ActionPerformed
        // TODO add your handling code here:
        if(chk8.isSelected()==true){
            llamarForm(8);
        }
    }//GEN-LAST:event_chk8ActionPerformed

    private void chkHabilidadNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabilidadNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHabilidadNumActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox chk1;
    public static javax.swing.JCheckBox chk2;
    public static javax.swing.JCheckBox chk3;
    public static javax.swing.JCheckBox chk5;
    public static javax.swing.JCheckBox chk6;
    public static javax.swing.JCheckBox chk7;
    public static javax.swing.JCheckBox chk8;
    public static javax.swing.JCheckBox chkAtencion;
    public static javax.swing.JCheckBox chkHabilidadNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
